version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: cf-postgres
    environment:
      POSTGRES_DB: chronoforge
      POSTGRES_USER: cf
      POSTGRES_PASSWORD: cf
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cf -d chronoforge"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: cf-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data:
